/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package zoologijos.sodas;

import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Kazimieras
 */
public class Darbuotojai extends javax.swing.JFrame {
    Mysql_veiksmai DB = new Mysql_veiksmai();
    irankiu_veiksmai irankiai = new irankiu_veiksmai();
    Abstraktus darb_veiks = new Darbuotoju_veiksmai();
    Pretendentu_veiksmai pretend_veiks= new Pretendentu_veiksmai();
    Darbuotoju_veiksmai darb_veiks_ne = new Darbuotoju_veiksmai();
    DefaultTableModel table_model_darb; 
    DefaultTableModel table_model_pretend; 
    Integer trinimas_laik_pretend=0;
    
 
    public Darbuotojai() {
        initComponents();
        try{
        DB.prisijungimas_db();
        
        table_model_darb=(DefaultTableModel)darb_table.getModel(); // 
        table_model_pretend=(DefaultTableModel)pretend_table.getModel();
        pretend_veiks.pretendentu_lango_uzpildis(table_model_pretend,DB.st, DB.rs, DB.connection,1);
        
        darb_veiks_ne.darbuotoju_lango_uzpildis(table_model_darb, DB.st, DB.rs, DB.connection);
       // DB.pridejimo_lango_uzpildis(table_model_Darb);
       System.err.println(""+DB);
        System.err.println(""+pretend_veiks);
        System.err.println(""+darb_veiks_ne);
        }
        catch(SQLException ex){}
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        darb_table = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        textbox_data = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        pridėti = new javax.swing.JButton();
        textbox_pavard = new javax.swing.JTextField();
        redaguoti = new javax.swing.JButton();
        pareigos = new javax.swing.JTextField();
        trinti = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        textbox_vardas = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        pretend_table = new javax.swing.JTable();
        prideti_pretend = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Atgal į pagrindinį");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        darb_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Vardas", "Pavardė", "Pareigos", "Įsidarbinimo data"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        darb_table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                darb_tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(darb_table);

        jLabel2.setText("Vardas");

        jLabel3.setText("Narvas");

        jLabel4.setText("Įsigijimo laikas");

        pridėti.setText("Pridėti");
        pridėti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pridėtiActionPerformed(evt);
            }
        });

        redaguoti.setText("Redaguoti");
        redaguoti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                redaguotiActionPerformed(evt);
            }
        });

        pareigos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                pareigosKeyPressed(evt);
            }
        });

        trinti.setText("Trinti");
        trinti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                trintiActionPerformed(evt);
            }
        });

        jLabel1.setText("Rūšis:");

        textbox_vardas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textbox_vardasActionPerformed(evt);
            }
        });

        pretend_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Vardas", "Pavarde", "Gimimo data", "Darbo vieta"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        pretend_table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pretend_tableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(pretend_table);

        prideti_pretend.setText("Pridėti į darbuotojus");
        prideti_pretend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prideti_pretendActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 1105, Short.MAX_VALUE)
                .addComponent(jButton1))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(31, 31, 31))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pridėti)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(redaguoti)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(trinti)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(pareigos)
                            .addComponent(textbox_data)
                            .addComponent(textbox_pavard)
                            .addComponent(textbox_vardas, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(prideti_pretend, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(11, 11, 11)))
                        .addGap(53, 53, 53))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(textbox_vardas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(textbox_pavard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(pareigos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(textbox_data, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(trinti)
                            .addComponent(redaguoti)
                            .addComponent(pridėti))
                        .addGap(98, 98, 98)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(prideti_pretend))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    Pirmas_pradinis prad=new Pirmas_pradinis() ;
    this.setVisible(false);
    prad.setVisible(true);
    
    }//GEN-LAST:event_jButton1ActionPerformed

    private void pridėtiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pridėtiActionPerformed
        try {
            DB.prisijungimas_db();
        } catch (SQLException ex) {

        }
        
         
          if(trinimas_laik_pretend.equals(1)){
              try{
         darb_veiks_ne.trinti_pretendenta(table_model_pretend, pretend_table, DB.st, DB.rs, DB.connection,pretend_veiks.pretendentu_identifikatorius.get(pretend_table.getSelectedRow()));
         table_model_pretend.removeRow(pretend_table.getSelectedRow());}
              catch(Exception ex){}
      
          }
            
           
          table_model_darb.insertRow(table_model_darb.getRowCount(), new Object[]{textbox_vardas.getText(), textbox_pavard.getText(),pareigos.getText()});
        //DB.pridėti_irasa(textbox_rus.getText(), textbox_vard.getText(), textbox_narv.getText(),table_model_Darb);
        darb_veiks.prideti_irasa(textbox_vardas.getText(), textbox_pavard.getText(), pareigos.getText(), table_model_darb, DB.st, DB.connection, DB.rs);
        trinimas_laik_pretend=0;
    }//GEN-LAST:event_pridėtiActionPerformed

    private void redaguotiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_redaguotiActionPerformed

        //System.out.print(darb_table.getSelectedRow()+1);

        //irankiu_veiksmai.table_eilutes_redagavimas(textbox_rus, table_model_Darb, darb_table, 0);
        irankiai.table_eilutes_redagavimas(textbox_vardas, table_model_darb, darb_table, 0);
        irankiai.table_eilutes_redagavimas(textbox_pavard, table_model_darb, darb_table, 1);
        irankiai.table_eilutes_redagavimas(pareigos, table_model_darb, darb_table, 2);
        irankiai.table_eilutes_redagavimas(textbox_data, table_model_darb, darb_table, 3);
        // DB.redaguoti_irasa(darb_table.getSelectedRow(), textbox_rus.getText(), textbox_vard.getText(), textbox_narv.getText(),textbox_data.getText());
        darb_veiks_ne.redaguoti_irasa(darb_table.getSelectedRow(), textbox_vardas.getText(), textbox_pavard.getText(), pareigos.getText(),textbox_data.getText(), table_model_darb, DB.st, DB.connection);
    }//GEN-LAST:event_redaguotiActionPerformed

    private void pareigosKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pareigosKeyPressed
      
    }//GEN-LAST:event_pareigosKeyPressed

    private void trintiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_trintiActionPerformed
            
        //DB.trinti_irasa(darb_table.getSelectedRow(),table_model_Darb);
         System.out.print(darb_veiks_ne. darbuotoju_identifikatorius.get(0));
        darb_veiks.trinti_irasa(darb_table.getSelectedRow(),table_model_darb, DB.st, DB.rs, DB.connection);
        try{
            table_model_darb.removeRow(darb_table.getSelectedRow());}
        catch(Exception ex){}
    }//GEN-LAST:event_trintiActionPerformed

    private void textbox_vardasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textbox_vardasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textbox_vardasActionPerformed

    private void pretend_tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pretend_tableMouseClicked

       
    }//GEN-LAST:event_pretend_tableMouseClicked

    private void prideti_pretendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prideti_pretendActionPerformed
      //  laukas.setText(String.valueOf(model.getValueAt(table.getSelectedRow(), stulp)));
       ArrayList<String> pretendentas= new ArrayList<String>();
       for(int i=0;i<4;i++)
           pretendentas.add(String.valueOf(table_model_pretend.getValueAt(pretend_table.getSelectedRow(), i)));
           darb_veiks_ne.perkelti_pretend_darb(pretendentas, textbox_vardas, 0);
            darb_veiks_ne.perkelti_pretend_darb(pretendentas, textbox_pavard, 1);
            darb_veiks_ne.perkelti_pretend_darb(pretendentas, pareigos, 2);
            darb_veiks_ne.perkelti_pretend_darb(pretendentas, textbox_data, 3);
            trinimas_laik_pretend=1;
          
       
    }//GEN-LAST:event_prideti_pretendActionPerformed

    private void darb_tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_darb_tableMouseClicked
        irankiai.table_eilutes_gavimas(textbox_vardas, table_model_darb, darb_table,0);
        irankiai.table_eilutes_gavimas(textbox_pavard, table_model_darb, darb_table,1);
        irankiai.table_eilutes_gavimas(pareigos, table_model_darb, darb_table,2);
        irankiai.table_eilutes_gavimas(textbox_data,  table_model_darb, darb_table,3);
    }//GEN-LAST:event_darb_tableMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Darbuotojai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Darbuotojai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Darbuotojai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Darbuotojai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Darbuotojai().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable darb_table;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField pareigos;
    private javax.swing.JTable pretend_table;
    private javax.swing.JButton prideti_pretend;
    private javax.swing.JButton pridėti;
    private javax.swing.JButton redaguoti;
    private javax.swing.JTextField textbox_data;
    private javax.swing.JTextField textbox_pavard;
    private javax.swing.JTextField textbox_vardas;
    private javax.swing.JButton trinti;
    // End of variables declaration//GEN-END:variables
}
