/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package zoologijos.sodas;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import zoologijos.sodas.Abstraktus;
import zoologijos.sodas.Gyvunu_pridejimo_lango_veiksmai;
import zoologijos.sodas.irankiu_veiksmai;
import zoologijos.sodas.Mysql_veiksmai;
import javax.swing.JFrame;

/**
 *
 * @author Kazimieras
 */
public class Gyv_pridėjimas extends javax.swing.JFrame  {
Mysql_veiksmai DB = new Mysql_veiksmai();
    irankiu_veiksmai irankiai = new irankiu_veiksmai();
    Gyvunu_pridejimo_lango_veiksmai gyv_add=new Gyvunu_pridejimo_lango_veiksmai();
    List<String> gyv_vardai=new ArrayList<String>();
    DefaultTableModel table_model; 
    /**
     * Creates new form pagrindinis_ekranas
     */
    public Gyv_pridėjimas() {
        initComponents();
        try{
        DB.prisijungimas_db();
        
        table_model=(DefaultTableModel)table1.getModel(); // 
       // DB.pridejimo_lango_uzpildis(table_model);
        gyv_add.pridejimo_lango_uzpildis(table_model, DB.st, DB.rs, DB.connection);
        }
        catch(SQLException ex){}
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        textbox_vard = new javax.swing.JTextField();
        textbox_narv = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        textbox_data = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        table1 = new javax.swing.JTable();
        pridėti = new javax.swing.JButton();
        redaguoti = new javax.swing.JButton();
        trinti = new javax.swing.JButton();
        textbox_rus = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        textbox_narv.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                textbox_narvKeyPressed(evt);
            }
        });

        jLabel1.setText("Rūšis:");

        jLabel2.setText("Vardas");

        jLabel3.setText("Narvas");

        jLabel4.setText("Įsigijimo laikas");

        jButton3.setText("Atgal į pagrindinį");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        table1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        table1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Rūšis", "Vardas", "Narvas", "Įsigijimo laikas"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        table1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table1);

        pridėti.setText("Pridėti");
        pridėti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pridėtiActionPerformed(evt);
            }
        });

        redaguoti.setText("Redaguoti");
        redaguoti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                redaguotiActionPerformed(evt);
            }
        });

        trinti.setText("Trinti");
        trinti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                trintiActionPerformed(evt);
            }
        });

        textbox_rus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textbox_rusActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 569, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(89, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton3))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel1)
                                .addComponent(jLabel2)
                                .addComponent(jLabel3)
                                .addComponent(jLabel4))
                            .addGap(31, 31, 31))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(pridėti)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(textbox_narv)
                            .addComponent(textbox_data)
                            .addComponent(textbox_vard)
                            .addComponent(textbox_rus, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(redaguoti)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(trinti)))
                    .addContainerGap(396, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 148, Short.MAX_VALUE)
                .addComponent(jButton3)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(143, 143, 143)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(textbox_rus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(textbox_vard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(textbox_narv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(textbox_data, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(trinti)
                        .addComponent(redaguoti)
                        .addComponent(pridėti))
                    .addContainerGap(30, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textbox_narvKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textbox_narvKeyPressed
        if(textbox_narv.getText().length()>=2){
            textbox_narv.setText(textbox_narv.getText().substring(0, Math.min(textbox_narv.getText().length(), 2)));
        }
    }//GEN-LAST:event_textbox_narvKeyPressed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        Pirmas_pradinis pradinis = new Pirmas_pradinis();
        this.setVisible(false);
        pradinis.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void table1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table1MouseClicked
        irankiai.table_eilutes_gavimas(textbox_rus, table_model, table1,0);
        irankiai.table_eilutes_gavimas(textbox_vard, table_model, table1,1);
        irankiai.table_eilutes_gavimas(textbox_narv, table_model, table1,2);
        irankiai.table_eilutes_gavimas(textbox_data, table_model, table1,3);
        System.out.println(table1.getSelectedRow());
    }//GEN-LAST:event_table1MouseClicked

    private void pridėtiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pridėtiActionPerformed
        try {
            DB.prisijungimas_db();
        } catch (SQLException ex) {
            
        }

        table_model.insertRow(table_model.getRowCount(), new Object[]{textbox_rus.getText(), textbox_vard.getText(),textbox_narv.getText()});

        //DB.pridėti_irasa(textbox_rus.getText(), textbox_vard.getText(), textbox_narv.getText(),table_model);
        gyv_add.prideti_irasa(textbox_rus.getText(), textbox_vard.getText(), textbox_narv.getText(), table_model, DB.st, DB.connection, DB.rs);

    }//GEN-LAST:event_pridėtiActionPerformed

    private void redaguotiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_redaguotiActionPerformed

        //System.out.print(table1.getSelectedRow()+1);

        //irankiu_veiksmai.table_eilutes_redagavimas(textbox_rus, table_model, table1, 0);
        irankiai.table_eilutes_redagavimas(textbox_rus, table_model, table1, 0);
        irankiai.table_eilutes_redagavimas(textbox_vard, table_model, table1, 1);
        irankiai.table_eilutes_redagavimas(textbox_narv, table_model, table1, 2);
        irankiai.table_eilutes_redagavimas(textbox_data, table_model, table1, 3);
        // DB.redaguoti_irasa(table1.getSelectedRow(), textbox_rus.getText(), textbox_vard.getText(), textbox_narv.getText(),textbox_data.getText());
        gyv_add.redaguoti_irasa(table1.getSelectedRow(), textbox_rus.getText(), textbox_vard.getText(), textbox_narv.getText(),textbox_data.getText(), table_model, DB.st, DB.connection);

    }//GEN-LAST:event_redaguotiActionPerformed

    private void trintiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_trintiActionPerformed

        //DB.trinti_irasa(table1.getSelectedRow(),table_model);

        gyv_add.trinti_irasa(table1.getSelectedRow(),table_model, DB.st, DB.rs, DB.connection);
        try{
            table_model.removeRow(table1.getSelectedRow());}
        catch(Exception ex){}

    }//GEN-LAST:event_trintiActionPerformed

    private void textbox_rusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textbox_rusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textbox_rusActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Gyv_pridėjimas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Gyv_pridėjimas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Gyv_pridėjimas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Gyv_pridėjimas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Gyv_pridėjimas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton pridėti;
    private javax.swing.JButton redaguoti;
    private javax.swing.JTable table1;
    private javax.swing.JTextField textbox_data;
    private javax.swing.JTextField textbox_narv;
    private javax.swing.JTextField textbox_rus;
    private javax.swing.JTextField textbox_vard;
    private javax.swing.JButton trinti;
    // End of variables declaration//GEN-END:variables
}
