
package zoologijos.sodas;

import java.sql.SQLException;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Kazimieras
 */
public class Pretendentai extends javax.swing.JFrame {
    Mysql_veiksmai DB = new Mysql_veiksmai();
    irankiu_veiksmai irankiai = new irankiu_veiksmai();
    Pretendentu_veiksmai pretend_veiks= new Pretendentu_veiksmai();
    
    
    DefaultTableModel table_model; 
    
    public Pretendentai() {
        initComponents();
        table_model=(DefaultTableModel)pretend_table.getModel(); // 
         try{
        DB.prisijungimas_db();
        
     
       // DB.pridejimo_lango_uzpildis(table_model);
        pretend_veiks.pretendentu_lango_uzpildis(table_model,DB.st, DB.rs, DB.connection);
        }
        catch(SQLException ex){}
        
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        pretend_table = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        textarea_motyv = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        textare_issilavinimas = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        button_priimti = new javax.swing.JButton();
        button_atmesti = new javax.swing.JButton();
        button_pagal_priimtus = new javax.swing.JButton();
        button_pagal_nepriimtus = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pretend_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Vardas", "Pavarde", "Gimimo data", "Darbo vieta"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        pretend_table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pretend_tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(pretend_table);

        textarea_motyv.setColumns(20);
        textarea_motyv.setRows(5);
        jScrollPane2.setViewportView(textarea_motyv);

        textare_issilavinimas.setColumns(20);
        textare_issilavinimas.setRows(5);
        jScrollPane3.setViewportView(textare_issilavinimas);

        jLabel1.setText("Motyvacinis");

        jLabel2.setText("Išsilavinimas");

        button_priimti.setText("Priimti");
        button_priimti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_priimtiActionPerformed(evt);
            }
        });

        button_atmesti.setText("Atmesti");
        button_atmesti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_atmestiActionPerformed(evt);
            }
        });

        button_pagal_priimtus.setText("Filtruoti pagal priimtus");
        button_pagal_priimtus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_pagal_priimtusActionPerformed(evt);
            }
        });

        button_pagal_nepriimtus.setText("Filtruoti pagal nepriimtus");
        button_pagal_nepriimtus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_pagal_nepriimtusActionPerformed(evt);
            }
        });

        jButton1.setText("Visi");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Atgal į pagrindinį");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(72, 72, 72)
                                .addComponent(button_pagal_priimtus)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(button_pagal_nepriimtus)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton1)))
                        .addContainerGap(349, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(button_atmesti, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(button_priimti, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(56, 56, 56)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(144, 144, 144)
                                            .addComponent(jLabel1)))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addGap(137, 137, 137)
                                    .addComponent(jLabel2)
                                    .addGap(129, 129, 129)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(6, 6, 6))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(button_pagal_priimtus)
                    .addComponent(button_pagal_nepriimtus)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(button_priimti)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(button_atmesti)
                .addGap(184, 184, 184))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addComponent(jButton2))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pretend_tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pretend_tableMouseClicked
       
       
        pretend_veiks.pretendentu_area(textarea_motyv, pretend_table, DB.st, DB.rs, DB.connection);
        
        pretend_veiks.pretendentu_area(textare_issilavinimas, pretend_table, DB.st, DB.rs, DB.connection,1);
    }//GEN-LAST:event_pretend_tableMouseClicked

    private void button_priimtiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_priimtiActionPerformed
       pretend_veiks.statusas(pretend_table, DB.st, DB.connection,1);
    }//GEN-LAST:event_button_priimtiActionPerformed

    private void button_atmestiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_atmestiActionPerformed
       pretend_veiks.statusas(pretend_table, DB.st, DB.connection,0);
    }//GEN-LAST:event_button_atmestiActionPerformed

    private void button_pagal_priimtusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_pagal_priimtusActionPerformed
         pretend_veiks.pretendentu_lango_uzpildis(table_model,DB.st, DB.rs, DB.connection,1);
    }//GEN-LAST:event_button_pagal_priimtusActionPerformed

    private void button_pagal_nepriimtusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_pagal_nepriimtusActionPerformed
         pretend_veiks.pretendentu_lango_uzpildis(table_model,DB.st, DB.rs, DB.connection,0);
    }//GEN-LAST:event_button_pagal_nepriimtusActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        pretend_veiks.pretendentu_lango_uzpildis(table_model,DB.st, DB.rs, DB.connection);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Pirmas_pradinis pagr = new Pirmas_pradinis();
        this.setVisible(false);
        pagr.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pretendentai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pretendentai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pretendentai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pretendentai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pretendentai().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button_atmesti;
    private javax.swing.JButton button_pagal_nepriimtus;
    private javax.swing.JButton button_pagal_priimtus;
    private javax.swing.JButton button_priimti;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable pretend_table;
    private javax.swing.JTextArea textare_issilavinimas;
    private javax.swing.JTextArea textarea_motyv;
    // End of variables declaration//GEN-END:variables
}
